sonar.projectKey=todo-api
sonar.projectName=todo-api
sonar.sources=.
sonar.host.url=http://host.docker.internal:9000
sonar.login=sqp_9070cc6c1d02af0863d468fb888ded7e8b136561
sonar.exclusions=node_modules/**, Dockerfile, .dockerignore, package.json, package-lock.json